name: remitso_widgets
description: A collection of custom Flutter widgets including TextField, AppBar, RadioButton, and DropdownButton with a consistent design system.

version: 0.0.1
homepage: https://github.com/ankitraj900/remitso_widgets
repository: https://github.com/ankitraj900/remitso_widgets

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: InterRegular28
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

